# Generated by Django 3.1.1 on 2020-11-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealmApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='picture',
        ),
    ]
