# Generated by Django 3.1.1 on 2020-11-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealmApp', '0002_auto_20201103_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
